config/routes.rb
Project::Application.routes.draw do
  resources :studentcourses

  resources :instructorcourses

  resources :subjects

  resources :instructor1s

  resources :instructors

  resources :discussions

  get "sessions/new"

  resources :students

  resources :courses
  root :to => "courses#index"

get '/signup' => 'students#new'
get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
get 'logout' => 'sessions#destroy'
get 'home' => 'sessions#home'

get '/signupInstructor' => 'instructor1s#new'#done

get 'loginInstructor' => 'sessions#newInstructor' #done
post 'loginInstructor' => 'sessions#createInstructor' #done
get 'logoutInstructor' => 'sessions#destroyInstructor'#not used

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  attr_accessible :Date,:Time,:Message,:Name
  validates :Name, presence:true
  validates :Message, presence:true
  end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all
	  @discussion = Discussion.new
	  @s=Instructor1.find(session[:user_id])
  	@iddarray=Instructor1.where(email: @s.email)
	  @idd=@iddarray[0].id.to_s
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @discussions }
	format.json { render json: @discussion }
    end
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @discussion = Discussion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discussion }
    end
  end

  # GET /discussions/new
  # GET /discussions/new.json
  def new
    @discussion = Discussion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @discussion }
    end
  end

  # GET /discussions/1/edit
  def edit
    @discussion = Discussion.find(params[:id])
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(params[:discussion])

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render json: @discussion, status: :created, location: @discussion }
      else
        format.html { render action: "new" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /discussions/1
  # PUT /discussions/1.json
  def update
    @discussion = Discussion.find(params[:id])

    respond_to do |format|
      if @discussion.update_attributes(params[:discussion])
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.destroy

    respond_to do |format|
      format.html { redirect_to discussions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_for(@discussion) do |f| %>
  <% if @discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% @discussion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Message %><br />
    <%= f.text_field :Message %>
  </div>
  <div class="field">
    <%= f.label :Date %><br />
    <%= f.date_select :Date %>    
  </div>
  <div class="field">
    <%= f.label :Name %><br />
    <%= f.text_field :Name,:value=>@s.email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<h1>Discussion Forum</h1>

<table border="2" style="width:100%";>
  <tr>
    <th style="text-align: center;">Date</th>
    <th style="text-align: center;">Time</th>
    <th style="text-align: center;">Name</th>
    <th style="text-align: center;">Discussion Topic</th>
  </tr>

<% @discussions.each do |discussion| %>
  <tr>
    <td style="text-align: center;"><%= discussion.Date.strftime(" %d-%b-%Y ") %></td>
    <td style="text-align: center;"><%= discussion.created_at.strftime(" %I:%M:%S %p ")%></td>
    <td style="text-align: center;"><%= discussion.Name %></td>
    <td style="text-align: center;"><%= discussion.Message %></td>
    <td style="text-align: center;"><%= link_to 'Show', discussion %></td>
    <td style="text-align: center;"><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
    <td style="text-align: center;"><%= link_to 'Destroy', discussion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to image_tag("/images/discussion.png", width:"175"), new_discussion_path %>

<h3>Post to this Forum </h3>

<%= render 'form' %>

<%= link_to image_tag("/images/backProf.png", width:"125"), '/instructor1s/'+@idd %>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render 'form' %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @discussion.Date %>
</p>

<p>
  <b>Time:</b>
  <%= @discussion.Time = @discussion.created_at.strftime(" %I:%M:%S %p ") %>
</p>

<p>
  <b>Name:</b>
  <%= @discussion.Name %>
</p>

<p>
  <b>Message:</b>
  <%= @discussion.Message %>
</p>


<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
<%= link_to 'Back', discussions_path %>