config/routes.rb
Project::Application.routes.draw do
  resources :studentcourses

  resources :instructorcourses

  resources :subjects

  resources :instructor1s

  resources :instructors

  resources :discussions

  get "sessions/new"

  resources :students

  resources :courses
  root :to => "courses#index"

get '/signup' => 'students#new'
get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
get 'logout' => 'sessions#destroy'
get 'home' => 'sessions#home'

get '/signupInstructor' => 'instructor1s#new'#done

get 'loginInstructor' => 'sessions#newInstructor' #done
post 'loginInstructor' => 'sessions#createInstructor' #done
get 'logoutInstructor' => 'sessions#destroyInstructor'#not used

end

app/controllers/instructorcourses_controller.rb
class InstructorcoursesController < ApplicationController
  # GET /instructorcourses
  # GET /instructorcourses.json
  def index
    @instructorcourses = Instructorcourse.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instructorcourses }
    end
  end

  # GET /instructorcourses/1
  # GET /instructorcourses/1.json
  def show
    @instructorcourse = Instructorcourse.find(params[:id])
	@s=Instructor1.find(session[:user_id])
	@iddarray=Instructor1.where(email: @s.email)
	@idd=@iddarray[0].id.to_s
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instructorcourse }
    end
  end

  # GET /instructorcourses/new
  # GET /instructorcourses/new.json
  def new
    @instructorcourse = Instructorcourse.new
	@s=Instructor1.find(session[:user_id])
	#@instructorcourse.email=@s.email
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instructorcourse }
    end
  end

  # GET /instructorcourses/1/edit
  def edit
    @instructorcourse = Instructorcourse.find(params[:id])
  end

  # POST /instructorcourses
  # POST /instructorcourses.json
  def create
    @instructorcourse = Instructorcourse.new(params[:instructorcourse])

    respond_to do |format|
      if @instructorcourse.save
        format.html { redirect_to @instructorcourse, notice: 'Instructorcourse was successfully created.' }
        format.json { render json: @instructorcourse, status: :created, location: @instructorcourse }
      else
        format.html { render action: "new" }
        format.json { render json: @instructorcourse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instructorcourses/1
  # PUT /instructorcourses/1.json
  def update
    @instructorcourse = Instructorcourse.find(params[:id])

    respond_to do |format|
      if @instructorcourse.update_attributes(params[:instructorcourse])
        format.html { redirect_to @instructorcourse, notice: 'Instructorcourse was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instructorcourse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructorcourses/1
  # DELETE /instructorcourses/1.json
  def destroy
    @instructorcourse = Instructorcourse.find(params[:id])
    @instructorcourse.destroy

    respond_to do |format|
      format.html { redirect_to instructorcourses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/instructorcourses_helper.rb
module InstructorcoursesHelper
end

app/views/instructorcourses/_form.html.erb
<h2>Logged in: <%= @s.email %></h2>
<%= form_for(@instructorcourse) do |f| %>
  <% if @instructorcourse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructorcourse.errors.count, "error") %> Prohibited this instructor's course from being saved:</h2>

      <ul>
      <% @instructorcourse.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instructoremail %><br />
    <%= f.text_field :instructoremail, :value=>@s.email %>
  </div>
  <div class="field">
    <%= f.label :coursecode %><br />
    <%= f.text_field :coursecode %>
  </div>
  <div class="field">
    <%= f.label :coursename %><br />
    <%= f.text_field :coursename %>
  </div>
  <div class="field">
    <%= f.label :coursedescription %><br />
    <%= f.text_field :coursedescription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructorcourses/edit.html.erb
<h1>Editing Instructor Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @instructorcourse %> |
<%= link_to 'Back', instructorcourses_path %>

app/views/instructorcourses/index.html.erb
<body style="background-color:#ECECEC">
<h1>Instructor Panel: Course Listing</h1>

<table border="2" style="width:100%;">
  <tr>
    <th style="text-align: center;">Instructor Email</th>
    <th style="text-align: center;">Course code</th>
    <th style="text-align: center;">Course Name</th>
    <th style="text-align: center;">Course Description</th>
  </tr>

<% @instructorcourses.each do |instructorcourse| %>
  <tr>
    <td style="text-align: center;"><%= instructorcourse.instructoremail %></td>
    <td style="text-align: center;"><%= instructorcourse.coursecode %></td>
    <td style="text-align: center;"><%= instructorcourse.coursename %></td>
    <td style="text-align: center;"><%= instructorcourse.coursedescription %></td>
    <td style="text-align: center;"><%= link_to 'Show', instructorcourse %></td>
    <td style="text-align: center;"><%= link_to 'Edit', edit_instructorcourse_path(instructorcourse) %></td>
    <td style="text-align: center;"><%= link_to 'Destroy', instructorcourse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to image_tag("/images/InstrCourse.png", width:"175"), new_instructorcourse_path %>
<br />
<p></p>
</body>

app/views/instructorcourses/new.html.erb
<h1>Instructor Panel - Courses</h1>

<%= render 'form' %>

<%= link_to image_tag("/images/Back.png", width:"100"), instructorcourses_path %>

app/views/instructorcourses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Instructor Email:</b>
  <%= @instructorcourse.instructoremail %>
</p>

<p>
  <b>Course Code:</b>
  <%= @instructorcourse.coursecode %>
</p>

<p>
  <b>Course Name:</b>
  <%= @instructorcourse.coursename %>
</p>

<p>
  <b>Course Description:</b>
  <%= @instructorcourse.coursedescription %>
</p>


<%= link_to 'Edit', edit_instructorcourse_path(@instructorcourse) %> |
<%= link_to 'Back', instructorcourses_path %>
<%= link_to 'Back to My Profile', ('/instructor1s/'+@idd) %>