config/routes.rb
Project::Application.routes.draw do
  resources :studentcourses

  resources :instructorcourses

  resources :subjects

  resources :instructor1s

  resources :instructors

  resources :discussions

  get "sessions/new"

  resources :students

  resources :courses
  root :to => "courses#index"

get '/signup' => 'students#new'
get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
get 'logout' => 'sessions#destroy'
get 'home' => 'sessions#home'

get '/signupInstructor' => 'instructor1s#new'#done

get 'loginInstructor' => 'sessions#newInstructor' #done
post 'loginInstructor' => 'sessions#createInstructor' #done
get 'logoutInstructor' => 'sessions#destroyInstructor'#not used

end

app/controllers/studentcourses_controller.rb
class StudentcoursesController < ApplicationController
  # GET /studentcourses
  # GET /studentcourses.json
  def index
    @studentcourses = Studentcourse.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @studentcourses }
    end
  end

  # GET /studentcourses/1
  # GET /studentcourses/1.json
  def show
    @studentcourse = Studentcourse.find(params[:id])
	@s=Student.find(session[:user_id])
	@iddarray=Student.where(email: @s.email)
	@idd=@iddarray[0].id.to_s
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @studentcourse }
    end
  end

  # GET /studentcourses/new
  # GET /studentcourses/new.json
  def new
    @studentcourse = Studentcourse.new
	@s=Student.find(session[:user_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @studentcourse }
    end
  end

  # GET /studentcourses/1/edit
  def edit
    @studentcourse = Studentcourse.find(params[:id])
	@s=Student.find(session[:user_id])
  end

  # POST /studentcourses
  # POST /studentcourses.json
  def create
@s=Student.find(session[:user_id])
@c=params[:studentcourse][:coursecode]
if Instructorcourse.where(coursecode: @c).length !=0
    @studentcourse = Studentcourse.new(params[:studentcourse])
	
    respond_to do |format|
      if @studentcourse.save
        format.html { redirect_to @studentcourse, notice: 'Studentcourse was successfully created.' }
        format.json { render json: @studentcourse, status: :created, location: @studentcourse }
      else
        format.html { render action: "new" }
        format.json { render json: @studentcourse.errors, status: :unprocessable_entity }
      end
    end
else
    respond_to do |format|
	format.html { redirect_to '/students/'+@s.id.to_s, notice: 'Studentcourse not added b/c it doest exist. click "courses" tab to see what courses are available' }
    end
end
  end

  # PUT /studentcourses/1
  # PUT /studentcourses/1.json
  def update
    @studentcourse = Studentcourse.find(params[:id])
	@s=Student.find(session[:user_id])
    respond_to do |format|
      if @studentcourse.update_attributes(params[:studentcourse])
        format.html { redirect_to @studentcourse, notice: 'Studentcourse was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @studentcourse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studentcourses/1
  # DELETE /studentcourses/1.json
  def destroy
    @studentcourse = Studentcourse.find(params[:id])
    @studentcourse.destroy

    respond_to do |format|
      format.html { redirect_to studentcourses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/studentcourses_helper.rb
module StudentcoursesHelper
end

app/views/studentcourses/_form.html.erb
<%= form_for(@studentcourse) do |f| %>
  <% if @studentcourse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@studentcourse.errors.count, "error") %> prohibited this studentcourse from being saved:</h2>

      <ul>
      <% @studentcourse.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :coursecode %><br />
    <%= f.text_field :coursecode %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :value=>@s.email %>
  </div>
  <div class="field">
    <%= f.label :date_of_joining %><br />
    <%= f.date_select :date_of_joining %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studentcourses/edit.html.erb
<h1>Editing studentcourse</h1>

<%= render 'form' %>

<%= link_to 'Show', @studentcourse %> |
<%= link_to 'Back', studentcourses_path %>

app/views/studentcourses/index.html.erb
<h1>Listing studentcourses</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Coursecode</th>
    <th>Date of joining</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @studentcourses.each do |studentcourse| %>
  <tr>
    <td><%= studentcourse.email %></td>
    <td><%= studentcourse.coursecode %></td>
    <td><%= studentcourse.date_of_joining %></td>
    <td><%= link_to 'Show', studentcourse %></td>
    <td><%= link_to 'Edit', edit_studentcourse_path(studentcourse) %></td>
    <td><%= link_to 'Destroy', studentcourse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Studentcourse', new_studentcourse_path %>

app/views/studentcourses/new.html.erb
<h1>New studentcourse</h1>

<%= render 'form' %>

<%= link_to image_tag("/images/Back.png", width:"100"), studentcourses_path %>

app/views/studentcourses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @studentcourse.email %>
</p>

<p>
  <b>Coursecode:</b>
  <%= @studentcourse.coursecode %>
</p>

<p>
  <b>Date of joining:</b>
  <%= @studentcourse.date_of_joining %>
</p>


<%= link_to 'Go back to my profile', '/students/'+@idd %>